import '../Features/home_feature/domain/entities/animal.dart';
import '../Features/home_feature/domain/entities/letter.dart';
import '../Features/home_feature/domain/entities/number.dart';

List<Number> numbers = [
  Number(
      symbol: "0",
      name: "Zero",
      modelPath: "assets/models/numbers/0.glb",
      imagePath:
          "assets/images/numbers_image/_139f1752-f1ae-4490-84cb-7c667e75219b.jpg",
      image2Path:
          "assets/images/numbers_image/_139f1752-f1ae-4490-84cb-7c667e75219b-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/0.mp3"),
  Number(
      symbol: "1",
      name: "One",
      modelPath: "assets/models/numbers/1.glb",
      imagePath:
          "assets/images/numbers_image/_0411e5f0-45d0-490c-ac52-5d67f9ad467c.jpg",
      image2Path:
          "assets/images/numbers_image/_0411e5f0-45d0-490c-ac52-5d67f9ad467c-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/1.mp3"),
  Number(
      symbol: "2",
      name: "Two",
      modelPath: "assets/models/numbers/2.glb",
      imagePath:
          "assets/images/numbers_image/_d0f019fd-b0ad-49df-9d8b-bbaea02bb9f1.jpg",
      image2Path:
          "assets/images/numbers_image/_011a4e1b-e77b-4fd2-b7ec-8980d569e56d-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/2.mp3"),
  Number(
      symbol: "3",
      name: "Three",
      modelPath: "assets/models/numbers/3.glb",
      imagePath:
          "assets/images/numbers_image/_26ab2a9c-9aab-48c0-b886-dcaef52642c9.jpg",
      image2Path:
          "assets/images/numbers_image/_26ab2a9c-9aab-48c0-b886-dcaef52642c9-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/3.mp3"),
  Number(
      symbol: "4",
      name: "Four",
      modelPath: "assets/models/numbers/4.glb",
      imagePath:
          "assets/images/numbers_image/_da9783f2-d521-44de-b3cd-679450a68ad9.jpg",
      image2Path:
          "assets/images/numbers_image/_da9783f2-d521-44de-b3cd-679450a68ad9-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/4.mp3"),
  Number(
      symbol: "5",
      name: "Five",
      modelPath: "assets/models/numbers/5.glb",
      imagePath:
          "assets/images/numbers_image/_a107b1e9-2fd2-46ed-a8fd-086670b4886b.jpg",
      image2Path:
          "assets/images/numbers_image/_a107b1e9-2fd2-46ed-a8fd-086670b4886b-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/5.mp3"),
  Number(
      symbol: "6",
      name: "Six",
      modelPath: "assets/models/numbers/6.glb",
      imagePath:
          "assets/images/numbers_image/_744f264d-8552-4e5e-8678-2c978d4e0421.jpg",
      image2Path:
          "assets/images/numbers_image/_744f264d-8552-4e5e-8678-2c978d4e0421-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/6.mp3"),
  Number(
      symbol: "7",
      name: "Seven",
      modelPath: "assets/models/numbers/7.glb",
      imagePath:
          "assets/images/numbers_image/_2a94f56d-f865-4dfd-ad38-1bff853b088b.jpg",
      image2Path:
          "assets/images/numbers_image/_2a94f56d-f865-4dfd-ad38-1bff853b088b-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/7.mp3"),
  Number(
      symbol: "8",
      name: "Eight",
      modelPath: "assets/models/numbers/8.glb",
      imagePath:
          "assets/images/numbers_image/_02385317-2108-4ee3-b614-b28765b78861.jpg",
      image2Path:
          "assets/images/numbers_image/_02385317-2108-4ee3-b614-b28765b78861-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/8.mp3"),
  Number(
      symbol: "9",
      name: "Nine",
      modelPath: "assets/models/numbers/9.glb",
      imagePath:
          "assets/images/numbers_image/_9ab7bf0d-33e8-48fc-bd2c-a2560c85fd76.jpg",
      image2Path:
          "assets/images/numbers_image/_f69bab0e-f729-4a0e-9407-13dd09c13ec5-removebg-preview.png",
      soundPath: "assets/sounds/numbers_sound/9.mp3"),
  Number(
      symbol: "10",
      name: "Ten",
      modelPath: "assets/models/numbers/10.glb",
      imagePath: "assets/images/numbers_image/10.png",
      image2Path: "assets/images/numbers_image/10.png",
      soundPath: "assets/sounds/numbers_sound/10.mp3"),
];
List<Letter> letters = [
  Letter(
      name: "Letter\t A",
      smallLetter: "a",
      capitalLetter: "A",
      imagePath: "assets/images/letters_image/a.jpg",
      image2Path: "assets/images/letters_image/a.png",
      modelCapitalPath: "assets/models/capital_letter/A.glb",
      modelSmallPath: "assets/models/small_letter/a.glb",
      soundPath: "assets/sounds/letters_sound/A.wav"),
  Letter(
      name: "Letter\t B",
      smallLetter: "b",
      capitalLetter: "B",
      imagePath: "assets/images/letters_image/b.jpg",
      image2Path: "assets/images/letters_image/b.png",
      modelCapitalPath: "assets/models/capital_letter/B.glb",
      modelSmallPath: "assets/models/small_letter/b.glb",
      soundPath: "assets/sounds/letters_sound/B.wav"),
  Letter(
      name: "Letter\t C",
      smallLetter: "c",
      capitalLetter: "C",
      imagePath: "assets/images/letters_image/c.jpg",
      image2Path: "assets/images/letters_image/c.png",
      modelCapitalPath: "assets/models/capital_letter/C.glb",
      modelSmallPath: "assets/models/small_letter/c.glb",
      soundPath: "assets/sounds/letters_sound/C.wav"),
  Letter(
      name: "Letter\t D",
      smallLetter: "d",
      capitalLetter: "D",
      imagePath: "assets/images/letters_image/d.jpg",
      image2Path: "assets/images/letters_image/d.png",
      modelCapitalPath: "assets/models/capital_letter/D.glb",
      modelSmallPath: "assets/models/small_letter/d.glb",
      soundPath: "assets/sounds/letters_sound/D.wav"),
  Letter(
      name: "Letter\t E",
      smallLetter: "e",
      capitalLetter: "E",
      imagePath: "assets/images/letters_image/e.jpg",
      image2Path: "assets/images/letters_image/e.png",
      modelCapitalPath: "assets/models/capital_letter/E.glb",
      modelSmallPath: "assets/models/small_letter/e.glb",
      soundPath: "assets/sounds/letters_sound/E.wav"),
  Letter(
      name: "Letter\t F",
      smallLetter: "f",
      capitalLetter: "F",
      imagePath: "assets/images/letters_image/f.jpg",
      image2Path: "assets/images/letters_image/f.png",
      modelCapitalPath: "assets/models/capital_letter/F.glb",
      modelSmallPath: "assets/models/small_letter/f.glb",
      soundPath: "assets/sounds/letters_sound/F.wav"),
  Letter(
      name: "Letter\t G",
      smallLetter: "g",
      capitalLetter: "G",
      imagePath: "assets/images/letters_image/g.jpg",
      image2Path: "assets/images/letters_image/g.png",
      modelCapitalPath: "assets/models/capital_letter/G.glb",
      modelSmallPath: "assets/models/small_letter/g.glb",
      soundPath: "assets/sounds/letters_sound/G.wav"),
  Letter(
      name: "Letter\t H",
      smallLetter: "h",
      capitalLetter: "H",
      imagePath: "assets/images/letters_image/h.jpg",
      image2Path: "assets/images/letters_image/h.png",
      modelCapitalPath: "assets/models/capital_letter/H.glb",
      modelSmallPath: "assets/models/small_letter/h.glb",
      soundPath: "assets/sounds/letters_sound/H.wav"),
  Letter(
      name: "Letter\t I",
      smallLetter: "i",
      capitalLetter: "I",
      imagePath: "assets/images/letters_image/i.jpg",
      image2Path: "assets/images/letters_image/i.png",
      modelCapitalPath: "assets/models/capital_letter/I.glb",
      modelSmallPath: "assets/models/small_letter/i.glb",
      soundPath: "assets/sounds/letters_sound/I.wav"),
  Letter(
      name: "Letter\t J",
      smallLetter: "j",
      capitalLetter: "J",
      imagePath: "assets/images/letters_image/j.jpg",
      image2Path: "assets/images/letters_image/j.png",
      modelCapitalPath: "assets/models/capital_letter/J.glb",
      modelSmallPath: "assets/models/small_letter/j.glb",
      soundPath: "assets/sounds/letters_sound/J.wav"),
  Letter(
      name: "Letter\t K",
      smallLetter: "k",
      capitalLetter: "K",
      imagePath: "assets/images/letters_image/k.jpg",
      image2Path: "assets/images/letters_image/k.png",
      modelCapitalPath: "assets/models/capital_letter/K.glb",
      modelSmallPath: "assets/models/small_letter/k.glb",
      soundPath: "assets/sounds/letters_sound/K.wav"),
  Letter(
      name: "Letter\t L",
      smallLetter: "l",
      capitalLetter: "L",
      imagePath: "assets/images/letters_image/l.jpg",
      image2Path: "assets/images/letters_image/l.png",
      modelCapitalPath: "assets/models/capital_letter/L.glb",
      modelSmallPath: "assets/models/small_letter/l.glb",
      soundPath: "assets/sounds/letters_sound/L.wav"),
  Letter(
      name: "Letter\t M",
      smallLetter: "m",
      capitalLetter: "M",
      imagePath: "assets/images/letters_image/m.jpg",
      image2Path: "assets/images/letters_image/m.png",
      modelCapitalPath: "assets/models/capital_letter/M.glb",
      modelSmallPath: "assets/models/small_letter/m.glb",
      soundPath: "assets/sounds/letters_sound/M.wav"),
  Letter(
      name: "Letter\t N",
      smallLetter: "n",
      capitalLetter: "N",
      imagePath: "assets/images/letters_image/n.jpg",
      image2Path: "assets/images/letters_image/n.png",
      modelCapitalPath: "assets/models/capital_letter/N.glb",
      modelSmallPath: "assets/models/small_letter/n.glb",
      soundPath: "assets/sounds/letters_sound/N.wav"),
  Letter(
      name: "Letter\t O",
      smallLetter: "o",
      capitalLetter: "O",
      imagePath: "assets/images/letters_image/o.jpg",
      image2Path: "assets/images/letters_image/o.png",
      modelCapitalPath: "assets/models/capital_letter/O.glb",
      modelSmallPath: "assets/models/small_letter/o.glb",
      soundPath: "assets/sounds/letters_sound/O.wav"),
  Letter(
      name: "Letter\t P",
      smallLetter: "p",
      capitalLetter: "P",
      imagePath: "assets/images/letters_image/p.jpg",
      image2Path: "assets/images/letters_image/p.png",
      modelCapitalPath: "assets/models/capital_letter/P.glb",
      modelSmallPath: "assets/models/small_letter/p.glb",
      soundPath: "assets/sounds/letters_sound/P.wav"),
  Letter(
      name: "Letter\t Q",
      smallLetter: "q",
      capitalLetter: "Q",
      imagePath: "assets/images/letters_image/q.jpg",
      image2Path: "assets/images/letters_image/q.png",
      modelCapitalPath: "assets/models/capital_letter/Q.glb",
      modelSmallPath: "assets/models/small_letter/q.glb",
      soundPath: "assets/sounds/letters_sound/Q.wav"),
  Letter(
      name: "Letter\t R",
      smallLetter: "r",
      capitalLetter: "R",
      imagePath: "assets/images/letters_image/r.jpg",
      image2Path: "assets/images/letters_image/r.png",
      modelCapitalPath: "assets/models/capital_letter/R.glb",
      modelSmallPath: "assets/models/small_letter/r.glb",
      soundPath: "assets/sounds/letters_sound/R.wav"),
  Letter(
      name: "Letter\t S",
      smallLetter: "s",
      capitalLetter: "S",
      imagePath: "assets/images/letters_image/s.jpg",
      image2Path: "assets/images/letters_image/s.png",
      modelCapitalPath: "assets/models/capital_letter/S.glb",
      modelSmallPath: "assets/models/small_letter/s.glb",
      soundPath: "assets/sounds/letters_sound/S.wav"),
  Letter(
      name: "Letter\t T",
      smallLetter: "t",
      capitalLetter: "T",
      imagePath: "assets/images/letters_image/t.jpg",
      image2Path: "assets/images/letters_image/t.png",
      modelCapitalPath: "assets/models/capital_letter/T.glb",
      modelSmallPath: "assets/models/small_letter/t.glb",
      soundPath: "assets/sounds/letters_sound/T.wav"),
  Letter(
      name: "Letter\t U",
      smallLetter: "u",
      capitalLetter: "U",
      imagePath: "assets/images/letters_image/u.jpg",
      image2Path: "assets/images/letters_image/u.png",
      modelCapitalPath: "assets/models/capital_letter/U.glb",
      modelSmallPath: "assets/models/small_letter/u.glb",
      soundPath: "assets/sounds/letters_sound/U.wav"),
  Letter(
      name: "Letter\t V",
      smallLetter: "v",
      capitalLetter: "V",
      imagePath: "assets/images/letters_image/v.jpg",
      image2Path: "assets/images/letters_image/v.png",
      modelCapitalPath: "assets/models/capital_letter/v.glb",
      modelSmallPath: "assets/models/small_letter/v.glb",
      soundPath: "assets/sounds/letters_sound/V.wav"),
  Letter(
      name: "Letter\t W",
      smallLetter: "w",
      capitalLetter: "W",
      imagePath: "assets/images/letters_image/w.jpg",
      image2Path: "assets/images/letters_image/w.png",
      modelCapitalPath: "assets/models/capital_letter/w.glb",
      modelSmallPath: "assets/models/small_letter/w.glb",
      soundPath: "assets/sounds/letters_sound/W.wav"),
  Letter(
      name: "Letter\t X",
      smallLetter: "x",
      capitalLetter: "X",
      imagePath: "assets/images/letters_image/x.jpg",
      image2Path: "assets/images/letters_image/x.png",
      modelCapitalPath: "assets/models/capital_letter/Red X.glb",
      modelSmallPath: "assets/models/small_letter/x.glb",
      soundPath: "assets/sounds/letters_sound/X.wav"),
  Letter(
      name: "Letter\t Y",
      smallLetter: "y",
      capitalLetter: "Y",
      imagePath: "assets/images/letters_image/y.jpg",
      image2Path: "assets/images/letters_image/y.png",
      modelCapitalPath: "assets/models/capital_letter/Y.glb",
      modelSmallPath: "assets/models/small_letter/y.glb",
      soundPath: "assets/sounds/letters_sound/Y.wav"),
  Letter(
      name: "Letter\t Z",
      smallLetter: "z",
      capitalLetter: "Z",
      imagePath: "assets/images/letters_image/z.jpg",
      image2Path: "assets/images/letters_image/z.png",
      modelCapitalPath: "assets/models/capital_letter/z.glb",
      modelSmallPath: "assets/models/small_letter/z.glb",
      soundPath: "assets/sounds/letters_sound/Z.wav"),
];
List<Animal> animals = [
  Animal(
      name: "Ant",
      imagePath: "assets/images/animals_image/ant.png",
      modelPath: "assets/models/animals/Ant.glb",
      soundPath: "assets/sounds/animals_sound/ant.wav",
      image2Path: "assets/images/animals_image/ant.png"),
  Animal(
      name: "Bear",
      imagePath: "assets/images/animals_image/bear.png",
      modelPath: "assets/models/animals/Bear.glb",
      soundPath: "assets/sounds/animals_sound/bear.wav",
      image2Path: "assets/images/animals_image/bear.png"),
  Animal(
      name: "Camel",
      imagePath: "assets/images/animals_image/camel.png",
      modelPath: "assets/models/animals/camel.glb",
      soundPath: "assets/sounds/animals_sound/camel.wav",
      image2Path: "assets/images/animals_image/camel.png"),
  Animal(
      name: "Cat",
      imagePath: "assets/images/animals_image/cat.png",
      modelPath: "assets/models/animals/cat.glb",
      soundPath: "assets/sounds/animals_sound/cat.wav",
      image2Path: "assets/images/animals_image/cat.png"),
  Animal(
      name: "Cow",
      imagePath: "assets/images/animals_image/cow.png",
      modelPath: "assets/models/animals/Cow.glb",
      soundPath: "assets/sounds/animals_sound/cow.wav",
      image2Path: "assets/images/animals_image/cow.png"),
  Animal(
      name: "Dog",
      imagePath: "assets/images/animals_image/dog.png",
      modelPath: "assets/models/animals/dog.glb",
      soundPath: "assets/sounds/animals_sound/dog.wav",
      image2Path: "assets/images/animals_image/dog.png"),
  Animal(
      name: "Dolphin",
      imagePath: "assets/images/animals_image/dolphin.png",
      modelPath: "assets/models/animals/Dolphin.glb",
      soundPath: "assets/sounds/animals_sound/dolphin.wav",
      image2Path: "assets/images/animals_image/dolphin.png"),
  Animal(
      name: "Elephant",
      imagePath: "assets/images/animals_image/elephant.png",
      modelPath: "assets/models/animals/Elephant.glb",
      soundPath: "assets/sounds/animals_sound/elephant.wav",
      image2Path: "assets/images/animals_image/elephant.png"),
  Animal(
      name: "Fox",
      imagePath: "assets/images/animals_image/fox.png",
      modelPath: "assets/models/animals/Fox.glb",
      soundPath: "assets/sounds/animals_sound/fox.wav",
      image2Path: "assets/images/animals_image/fox.png"),
  Animal(
      name: "Goose",
      imagePath: "assets/images/animals_image/goose.png",
      modelPath: "assets/models/animals/Goose.glb",
      soundPath: "assets/sounds/animals_sound/goose.wav",
      image2Path: "assets/images/animals_image/goose.png"),
  Animal(
      name: "Horse",
      imagePath: "assets/images/animals_image/horse.png",
      modelPath: "assets/models/animals/Horse.glb",
      soundPath: "assets/sounds/animals_sound/horse.wav",
      image2Path: "assets/images/animals_image/horse.png"),
  Animal(
      name: "Iguanas",
      imagePath: "assets/images/animals_image/iguana.png",
      modelPath: "assets/models/animals/Iguana.glb",
      soundPath: "assets/sounds/animals_sound/iguana.wav",
      image2Path: "assets/images/animals_image/iguana.png"),
  Animal(
      name: "Kangaroo",
      imagePath: "assets/images/animals_image/kangaroo.png",
      modelPath: "assets/models/animals/Kangaroo.glb",
      soundPath: "assets/sounds/animals_sound/kangaroo.wav",
      image2Path: "assets/images/animals_image/kangaroo.png"),
  Animal(
      name: "Leopard",
      imagePath: "assets/images/animals_image/leopard.png",
      modelPath: "assets/models/animals/Leopard.glb",
      soundPath: "assets/sounds/animals_sound/leopard.wav",
      image2Path: "assets/images/animals_image/leopard.png"),
  Animal(
      name: "Lion",
      imagePath: "assets/images/animals_image/lion.png",
      modelPath: "assets/models/animals/Lion.glb",
      soundPath: "assets/sounds/animals_sound/lion.wav",
      image2Path: "assets/images/animals_image/lion.png"),
  Animal(
      name: "Ladybug",
      imagePath: "assets/images/animals_image/ladybug.png",
      modelPath: "assets/models/animals/Ladybug.glb",
      soundPath: "assets/sounds/animals_sound/ladybug.wav",
      image2Path: "assets/images/animals_image/ladybug.png"),
  Animal(
      name: "monkey",
      imagePath: "assets/images/animals_image/monkey.png",
      modelPath: "assets/models/animals/monkey.glb",
      soundPath: "assets/sounds/animals_sound/monky.wav",
      image2Path: "assets/images/animals_image/monkey.png"),
  Animal(
      name: "Mouse",
      imagePath: "assets/images/animals_image/mouse.png",
      modelPath: "assets/models/animals/mouse.glb",
      soundPath: "assets/sounds/animals_sound/mouse.wav",
      image2Path: "assets/images/animals_image/mouse.png"),
  Animal(
      name: "Narwhal",
      imagePath: "assets/images/animals_image/narwhal.png",
      modelPath: "assets/models/animals/Narwhal.glb",
      soundPath: "assets/sounds/animals_sound/narwal.wav",
      image2Path: "assets/images/animals_image/narwhal.png"),
  Animal(
      name: "Octopus",
      imagePath: "assets/images/animals_image/octopus.png",
      modelPath: "assets/models/animals/Octopus.glb",
      soundPath: "assets/sounds/animals_sound/octupus.wav",
      image2Path: "assets/images/animals_image/octopus.png"),
  Animal(
      name: "Ostrich",
      imagePath: "assets/images/animals_image/ostrich.png",
      modelPath: "assets/models/animals/Ostrich.glb",
      soundPath: "assets/sounds/animals_sound/ostrich.wav",
      image2Path: "assets/images/animals_image/ostrich.png"),
  Animal(
      name: "Parrot",
      imagePath: "assets/images/animals_image/parot.png",
      modelPath: "assets/models/animals/Parrot.glb",
      soundPath: "assets/sounds/animals_sound/parrot.wav",
      image2Path: "assets/images/animals_image/parot.png"),
  Animal(
      name: "Penguin",
      imagePath: "assets/images/animals_image/pinguine.png",
      modelPath: "assets/models/animals/Penguin.glb",
      soundPath: "assets/sounds/animals_sound/penguine.wav",
      image2Path: "assets/images/animals_image/pinguine.png"),
  Animal(
      name: "Quail",
      imagePath: "assets/images/animals_image/quail.png",
      modelPath: "assets/models/animals/Quail.glb",
      soundPath: "assets/sounds/animals_sound/quail.wav",
      image2Path: "assets/images/animals_image/quail.png"),
  Animal(
      name: "Rabbit",
      imagePath: "assets/images/animals_image/rabbit.png",
      modelPath: "assets/models/animals/rabbit.glb",
      soundPath: "assets/sounds/animals_sound/rabbit.wav",
      image2Path: "assets/images/animals_image/rabbit.png"),
  Animal(
      name: "Sheep",
      imagePath: "assets/images/animals_image/sheep.png",
      modelPath: "assets/models/animals/Sheep.glb",
      soundPath: "assets/sounds/animals_sound/sheep.wav",
      image2Path: "assets/images/animals_image/sheep.png"),
  Animal(
      name: "Snake",
      imagePath: "assets/images/animals_image/snake.png",
      modelPath: "assets/models/animals/snake.glb",
      soundPath: "assets/sounds/animals_sound/snake.wav",
      image2Path: "assets/images/animals_image/snake.png"),
  Animal(
      name: "Turtle",
      imagePath: "assets/images/animals_image/turtle.png",
      modelPath: "assets/models/animals/Turtle.glb",
      soundPath: "assets/sounds/animals_sound/turtle.wav",
      image2Path: "assets/images/animals_image/turtle.png"),
  Animal(
      name: "Unicorn",
      imagePath: "assets/images/animals_image/u.png",
      modelPath: "assets/models/animals/Unicorn.glb",
      soundPath: "assets/sounds/animals_sound/unicorn.wav",
      image2Path: "assets/images/animals_image/u.png"),
  Animal(
      name: "Vulture",
      imagePath: "assets/images/animals_image/Vulture.png",
      modelPath: "assets/models/animals/Vulture.glb",
      soundPath: "assets/sounds/animals_sound/vulture.wav",
      image2Path: "assets/images/animals_image/Vulture.png"),
  Animal(
      name: "Whale",
      imagePath: "assets/images/animals_image/whale.png",
      modelPath: "assets/models/animals/whale.glb",
      soundPath: "assets/sounds/animals_sound/wheel.wav",
      image2Path: "assets/images/animals_image/whale.png"),
  Animal(
      name: "Wolf",
      imagePath: "assets/images/animals_image/wolf.png",
      modelPath: "assets/models/animals/Wolf.glb",
      soundPath: "assets/sounds/animals_sound/wolf.wav",
      image2Path: "assets/images/animals_image/wolf.png"),
  Animal(
      name: "x-ray-fish",
      imagePath: "assets/images/animals_image/xray-shiny_fish.png",
      modelPath: "assets/models/animals/xray-shiny_fish.glb",
      soundPath: "assets/sounds/animals_sound/x-ray-fish.wav",
      image2Path: "assets/images/animals_image/xray-shiny_fish.png"),
  Animal(
      name: "yak",
      imagePath: "assets/images/animals_image/yak.jpg",
      modelPath: "assets/models/animals/Yak.glb",
      soundPath: "assets/sounds/animals_sound/yak.wav",
      image2Path: "assets/images/animals_image/yak.jpg"),
  Animal(
      name: "Zebra",
      imagePath: "assets/images/animals_image/zebra.png",
      modelPath: "assets/models/animals/zebra.glb",
      soundPath: "assets/sounds/animals_sound/zebra.wav",
      image2Path: "assets/images/animals_image/zebra.png")
];
